# Generated by Django 5.1.4 on 2024-12-11 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_area', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HabilitarFechas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_habilitacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio de Habilitación')),
                ('fecha_fin_habilitacion', models.DateField(blank=True, null=True, verbose_name='Fecha Fin de Habilitación')),
            ],
            options={
                'verbose_name': 'Habilitar Fecha',
                'verbose_name_plural': 'Habilitacion de Fechas',
            },
        ),
        migrations.CreateModel(
            name='T_Fase',
            fields=[
                ('Id_fase', models.AutoField(primary_key=True, serialize=False)),
                ('S_Fase', models.CharField(max_length=100, verbose_name='Fase o Etapa del Proyecto')),
            ],
            options={
                'verbose_name': 'Fase Proyecto',
                'verbose_name_plural': 'Fases del Proyecto ',
            },
        ),
        migrations.CreateModel(
            name='T_Tipo',
            fields=[
                ('Id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('S_Tipo', models.CharField(max_length=100, verbose_name='Tipo de Investigación Social.')),
            ],
            options={
                'verbose_name': 'Tipo Proyecto',
                'verbose_name_plural': 'Tipo de Proyectos ',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ru', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_carrera', models.CharField(max_length=150)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interaccion_social.facultad')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interaccion_social.gestion')),
            ],
            options={
                'ordering': ['-numero', '-gestion__anio'],
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_Semestre', models.CharField(max_length=100, verbose_name='Semestre')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interaccion_social.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_materia', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interaccion_social.area')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interaccion_social.semestre')),
            ],
        ),
        migrations.CreateModel(
            name='T_Proyectos_IIISP',
            fields=[
                ('Id_Proyect', models.AutoField(primary_key=True, serialize=False)),
                ('S_Titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('Fecha_Inicio', models.DateField()),
                ('Fecha_Finalizacion', models.DateField()),
                ('S_Descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('S_Documentacion', models.FileField(null=True, upload_to='Documento/', verbose_name='Documentación')),
                ('S_Imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('S_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario relacionado')),
                ('T_Fase_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interaccion_social.t_fase', verbose_name='Fase del Proyecto')),
                ('T_Gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interaccion_social.periodo', verbose_name='Gestion')),
                ('T_Materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interaccion_social.materia', verbose_name='Materia')),
                ('T_Tipo_Proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interaccion_social.t_tipo', verbose_name='Tipo de Proyecto')),
            ],
            options={
                'verbose_name': 'Trabajos IIISP',
                'verbose_name_plural': 'Proyectos IIISP',
            },
        ),
    ]
